name         'maximmirny-accounts'
version      '0.0.1'
source       'Maxim Mirny'
author       'Maxim Mirny'
license      ''
summary      ''
description  ''
project_page ''

#Add dependencies, if any:
