forge "https://forgeapi.puppetlabs.com"

#For theforeman/puppet
mod 'theforeman-puppet', '7.0.0'

mod 'puppetlabs-puppetdb', '5.1.2'

mod 'puppetlabs-postgresql', '4.8.0'

mod 'puppetlabs-ntp', '6.0.0'